apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-integration-server
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem