apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-bar-pvc
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem